### ISSUE TITLE
model in toml

### ISSUE THREAD

**Issue by avelino** [talkdai/dialog#31]
The model is defined in hard code `gpt-3.5-turbo`, we need to take it to the configuration (in TOML), making the project customizable

https://github.com/talkdai/dialog/blob/012c73c02b30382d3dd95068dd0255e1242d8789/src/llm/__init__.py#L22

```toml
[prompt]
model_name = "gpt-3.5-turbo"
```

> if not set, it should be model `gpt-3.5-turbo` by default
